# 项目配置
novel:
  # 跨域配置
  cors:
    # 允许跨域的域名
    allow-origins:
      - http://localhost:1024
      - http://localhost:8080
spring:
  application:
    name: novel
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://localhost:3306/novel?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 1234
  # Redis 配置
  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 1
  rabbitmq:
    host: 192.168.48.128
    port: 5672
    username: guest
    password: guest
    virtual-host: novel
    template:
      retry:
        # 开启重试
        enabled: true
        # 最大重试次数
        max-attempts: 3
        # 第一次和第二次重试之间的持续时间
        initial-interval: "3s"
server:
  port: 8888
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /swagger-ui/index.html


